### ISSUE TITLE
Biological measures not working

### ISSUE THREAD

**Issue by TimoK93** [CellTrackingChallenge/fiji-plugins#1]
Hey,

thanks for your great work! Unfortunately the biological measures are not working correctly... 

Thank you for helping me!

Best,
Timo

## Description

I was able to run technical measures, tracking consistency and data measures. When I run biological measures, the following error happens:

```shell
[Tue Sep 05 11:50:52 CEST 2023] [INFO] []  GT path: /localstorage/kaiser/CellTrackingChallenge/2D/Training/BF-C2DL-HSC/01_GT/TRA
[Tue Sep 05 11:50:52 CEST 2023] [INFO] [] RES path: /localstorage/kaiser/CellResults/normal/train/BF-C2DL-HSC/01_RES
[Tue Sep 05 11:50:52 CEST 2023] [INFO] [] Loaded track file: /localstorage/kaiser/CellTrackingChallenge/2D/Training/BF-C2DL-HSC/01_GT/TRA/man_track.txt
[Tue Sep 05 11:50:52 CEST 2023] [INFO] [] Loaded track file: /localstorage/kaiser/CellResults/normal/train/BF-C2DL-HSC/01_RES/res_track.txt
[Tue Sep 05 11:50:52 CEST 2023] [ERROR] [] CTC CT measure problem: No reference (GT) image was found!
```
I am totally sure that the data is in the correct format. Otherwise the other metrics would have raised an error, right? 

## Setup

Tested on

- Win10
- Linux KDE
- Used the output of [EmbedTrack](https://git.scc.kit.edu/kit-loe-ge/embedtrack)

**Comment by xulman** [comment]
Hi @TimoK93,

(I apparently wasn't watching this repo, until now, and overlooked your issue.. I am sorry for that)

Indeed, you have the data well named and structured, perfectly according to the CTC spec.

There was sadly a bug in the Biological measures that the information about the number of digits wasn't propagated to the actual workhorse code. Interestingly, the same issue was not present in the Technical measures, which is why they worked well also on this 4-digit BF-C2DL-HSC dataset.

I'm sorry for this stupid bug. It is now fixed.
The new code is available here on the GH, and new version of the CTC Fiji plugins was just released too.

Thank you for the report, much appreciated.
Vlado
